server:
  port: 8230

spring:
  redis:
    host: kk.hb520.site
    port: 6379
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://kk.hb520.site:3306/ccq
    username: root
    password: lyhh2303
  application:
    name: "article"
  cloud:
    zookeeper:
      connect-string:       kk.hb520.site:2181
      discovery:
        instance-host: 192.168.1.9
        instance-port: 8230